name: Build NZFK Frontend and deploy to Kubernetes cluster

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:
    branches:
      - 'main'

env:
  IMAGE_NAME: danilmalkinnn/mybar-frontend
  REACT_APP_BASE_URL: http://mybar.dvmalkin.online/api/

jobs:

  build_deploy:
    name: Build and push Docker image to Docker Hub & deploy to K8s
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
#          context: ./
          build-args: |
            "REACT_APP_BASE_URL=${{ env.REACT_APP_BASE_URL }}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Cancel previous workflow runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Replace environment variables
        uses: nowactions/envsubst@v1
        with:
          input: k8s/k8s.yaml
          output: k8s/deployment.yaml
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}@${{ steps.docker_build.outputs.digest }}
          REPLICA_COUNT: 1

      - name: Checkout K8s manifests content
        run: |
          echo "Checkout K8s manifests content"
          cat ${{ github.workspace }}/k8s/deployment.yaml

      - name: Setup kubectl client
        uses: azure/setup-kubectl@v3
        with:
          version: v1.26.0

      - name: Set Kubernetes context
        uses: Azure/k8s-set-context@v2
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to the Kubernetes cluster
        uses: Azure/k8s-deploy@v4
        with:
          manifests: |
            k8s/deployment.yaml
          namespace: my-bar
